aws_region          = "eu-north-1"
bucket_name         = "la-bella-cucina-fragrance-1"
restaurant_name     = "La Bella Cucina"
environment         = "production"
cloudfront_price_class = "PriceClass_100"
github_username     = "YOUR_GITHUB_USERNAME"
github_repo         = "iac_static_web"
tfstate_bucket_name = "YOUR-TFSTATE-BUCKET-NAME"
